
link1_controller:
  type: "position_controllers/JointPositionControllers"
  joint: link1_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
link2_controller:
  type: "position_controllers/JointPositionControllers"
  joint: link2_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
end_effector_controller:
  type: "position_controllers/JointPositionControllers"
  joint: end_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
